apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: ingress-gw
  labels:
    app: tcp-echo
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: TCP
    port: 8000
    name: tcp
    allowedRoutes:
      namespaces:
        # from: Same
        # from: All
        from: Selector # Only allow routes from namespaces with the following label set.
        selector:
          matchLabels:
            shared-gateway-access: "true"
      kinds:
      - kind: TCPRoute